### ISSUE TITLE
notify old users on pypi about name change

### ISSUE THREAD

**Issue by johanneswilm** [fellowapp/prosemirror-py#269]
Hey @sciyoshi ,
since version 0.3.1, no releases have been pushed to pypi. https://pypi.org/project/prosemirror-py/#history

Could at least the latest release (0.3.5) be published there?

**Comment by johanneswilm** [comment]
Ah, found the name change while browsing through the git commits: https://github.com/fellowapp/prosemirror-py/commit/68c2d1702d775c2b46525704dce05913c9fcf6cf

Maybe it could be announced that the old package has been replaced?

**Comment by sciyoshi** [comment]
Thank you @johanneswilm - the old project name has been updated to point to the new package.
